# GUI 版本配置檔案
# 此配置針對 GUI 使用進行了優化

# VAD (語音活動檢測) 配置
vad:
  sample_rate: 16000        # 取樣率 (Hz)
  frame_duration: 30        # 幀時長 (ms), 可選: 10, 20, 30
  vad_mode: 3              # VAD 模式 (0-3), 3 最激進，更容易檢測到語音
  energy_threshold: 500    # 能量閾值

# ASR (語音識別) 配置
asr:
  model_size: base          # 模型: tiny, base, small, medium, large
                           # GUI 中可以隨時更改
  language: zh              # 預設語言: zh (普通話), yue (粵語), en (英文)
                           # GUI 中可以隨時切換
  device: cpu               # 裝置: cpu, cuda (如果有 GPU)
  compute_type: int8        # 計算類型: int8 (快), float16, float32 (慢但準確)
  speech_timeout: 1.0       # 靜音逾時 (秒) - 說話停頓多久後開始識別
  min_speech_duration: 0.5  # 最短語音時長 (秒) - 過濾掉太短的聲音
  model_path: null          # 本地模型路徑 (可選，留空自動下載)
  enable_language_switch: true  # 啟用語言切換功能

# 除錯配置
debug:
  save_audio: false         # 是否儲存音訊檔案 (用於除錯)
  audio_save_path: debug/   # 音訊儲存路徑
  verbose: false            # 詳細輸出 (GUI 中建議關閉)

# GUI 特定配置
gui:
  window_width: 900         # 視窗寬度
  window_height: 650        # 視窗高度
  font_size: 10            # 字型大小
  max_result_lines: 1000   # 最大結果行數 (超過後自動清理舊的)
  auto_scroll: true        # 自動捲動到最新結果
